version: '3.9'
services:
  employee-duty-service:
    image: employee-duty-service
    environment:
      KAFKA_URL: kafka:9092
    ports:
      - "8002:8002"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - assignment-network
  employee-service:
    image: employee-service
    ports:
      - "8001:8001"
    networks:
      - assignment-network
  message-service:
    image: message-service
    environment:
      KAFKA_URL: kafka:9092
      EMPLOYEE_BASE_URL: http://employee-service:8001
      EMPLOYEE_DUTY_BASE_URL: http://employee-duty-service:8002
    ports:
      - "8003:8003"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - assignment-network
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - assignment-network
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
    networks:
      - assignment-network
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 20s
      interval: 5s
      timeout: 10s
      retries: 10
networks:
  assignment-network:
    driver: bridge