server:
  port: 8001

spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:h2:mem:employeedb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
logging:
  level:
    com.example.employeeService: DEBUG
